// The Markdown face of the domain checklists (SKILLS_PLAN.md §4): one file per domain for shared
// items, one per project for that project's own. The database holds the lifecycle; these files are
// regenerated from it so the owner can read, reword or delete any line, and those hand edits are read
// back before the next write — the same pattern the knowledge vault uses.
//
// Where the files live is the owner's decision: shared lists under the directory DevTeam was
// launched from (`<launch dir>/checklists/<domain>.md`), a project's list at
// `<project root>/.devteam/checklist.md`. The brief's `checklistFiles` resolves the same paths
// (store-views.mjs), so pass the same `sharedDir` as `store.checklistDir`.
//
// What read-back honours, deliberately narrow:
// - a line deleted by hand retires that item (it stays in history and comes back on re-violation);
// - reworded text becomes the item's rule, redacted and capped;
// - a line moved under another heading changes the item's section.
// A line the owner *adds* without an id is reported, never turned into a rule: items come only from
// real findings, and an owner who wants one approves a candidate instead.
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import path from "node:path";
import { redact } from "./knowledge.mjs";
import { CHECKLIST_RULE_MAX } from "./store-checklists.mjs";

const HEADER = "<!-- devteam-checklist v1";
const ITEM_COMMENT = /^\s*<!--\s*id:\s*([0-9a-f-]{36})\b.*-->\s*$/iu;
const HEADER_IDS = /items:\s*([0-9a-f,\s-]*)-->/iu;
const clean = (value, max) => redact(String(value ?? "")).replace(/\s+/gu, " ").trim().slice(0, max);

export const sharedChecklistPath = (sharedDir, domain) => path.join(sharedDir, `${domain}.md`);
export const projectChecklistPath = (projectRoot) => path.join(projectRoot, ".devteam", "checklist.md");

// items: [{ id, domain, section, rule, confirmations, lastSeen, expiryPending }]
export function renderChecklistMarkdown({ title, items, generatedAt = new Date().toISOString() }) {
  const sorted = [...items].sort((a, b) => a.section.localeCompare(b.section)
    || (b.confirmations - a.confirmations) || a.rule.localeCompare(b.rule));
  const lines = [
    `${HEADER} · generated ${generatedAt.slice(0, 10)} · items: ${sorted.map((item) => item.id).join(",")} -->`,
    `# ${clean(title, 120)}`,
    "",
    "Regenerated by DevTeam from reviewers' findings. You may reword, move or delete a line; DevTeam",
    "reads your edits back before it rewrites this file. Agents: do not edit this file — report findings.",
  ];
  let section = null;
  for (const item of sorted) {
    if (item.section !== section) {
      section = item.section;
      lines.push("", `## ${clean(section, 40)}`);
    }
    const meta = [
      `id: ${item.id}`,
      `domain: ${item.domain}`,
      `confirmed ${Number(item.confirmations) || 0}×`,
      item.lastSeen ? `last seen ${String(item.lastSeen).slice(0, 10)}` : null,
      item.expiryPending ? "expiry pending owner confirmation" : null,
    ].filter(Boolean).join(" · ");
    lines.push(`- [ ] ${clean(item.rule, CHECKLIST_RULE_MAX)}`, `  <!-- ${meta} -->`);
  }
  if (!sorted.length) lines.push("", "_No active items yet. This list grows as reviews find recurring mistakes._");
  return `${lines.join("\n")}\n`;
}

// Returns { exportedIds, items: Map(id → {rule, section}), unlinked: [text] }.
export function parseChecklistMarkdown(text) {
  const lines = String(text || "").split(/\r?\n/u);
  const header = lines.find((line) => line.startsWith(HEADER));
  const exportedIds = header?.match(HEADER_IDS)?.[1].split(",").map((id) => id.trim()).filter(Boolean) || [];
  const items = new Map();
  const unlinked = [];
  let section = "General";
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    const heading = line.match(/^##\s+(.+?)\s*$/u);
    if (heading) { section = heading[1]; continue; }
    const bullet = line.match(/^\s*-\s*\[[ xX]?\]\s*(.+?)\s*$/u);
    if (!bullet) continue;
    const id = lines[index + 1]?.match(ITEM_COMMENT)?.[1];
    if (id) { items.set(id, { rule: bullet[1], section }); index += 1; }
    else unlinked.push(bullet[1]);
  }
  return { exportedIds, items, unlinked };
}

function writeIfChanged(filePath, content) {
  const previous = existsSync(filePath) ? readFileSync(filePath, "utf8") : null;
  // The date in the header changes daily; do not rewrite a file whose items are identical.
  const body = (value) => value?.replace(/^<!-- devteam-checklist v1 · generated \d{4}-\d{2}-\d{2}/u, "");
  if (previous !== null && body(previous) === body(content)) return false;
  mkdirSync(path.dirname(filePath), { recursive: true });
  const temporary = `${filePath}.${process.pid}.tmp`;
  writeFileSync(temporary, content, "utf8");
  renameSync(temporary, filePath);
  return true;
}

// Apply the owner's hand edits in one file to the store. Only ids this file previously exported are
// considered, so an item promoted since the last export is never mistaken for a deletion, and ids from
// a different scope (a pasted project item in a shared file) are ignored.
function readBack(store, filePath, allowedIds) {
  if (!existsSync(filePath)) return { retired: [], updated: [], unlinked: [] };
  const parsed = parseChecklistMarkdown(readFileSync(filePath, "utf8"));
  const retired = [];
  const updated = [];
  for (const id of parsed.exportedIds) {
    if (!allowedIds.has(id)) continue;
    const current = store.db.prepare("SELECT * FROM checklist_items WHERE id = ?").get(id);
    if (!current || current.status !== "active") continue;
    const edited = parsed.items.get(id);
    if (!edited) {
      store.retireChecklistItem(id, "deleted from the checklist file by the owner");
      retired.push(id);
      continue;
    }
    const rule = clean(edited.rule, CHECKLIST_RULE_MAX);
    const section = clean(edited.section, 40) || current.section;
    if (rule && (rule !== current.rule || section !== current.section)) {
      store.db.prepare("UPDATE checklist_items SET rule = ?, section = ?, updated_at = ? WHERE id = ?")
        .run(rule, section, new Date().toISOString(), id);
      updated.push(id);
    }
  }
  return { retired, updated, unlinked: parsed.unlinked };
}

function exportItems(store, where, args) {
  return store.db.prepare(`
    SELECT i.id, i.domain, i.section, i.rule, i.expiry_pending_at,
      (SELECT COUNT(*) FROM assignment_findings f WHERE f.checklist_item_id = i.id) AS confirmations,
      (SELECT MAX(f.created_at) FROM assignment_findings f WHERE f.checklist_item_id = i.id) AS last_seen
    FROM checklist_items i WHERE i.status = 'active' AND ${where}
  `).all(...args).map((row) => ({
    id: row.id, domain: row.domain, section: row.section, rule: row.rule,
    confirmations: Number(row.confirmations), lastSeen: row.last_seen, expiryPending: Boolean(row.expiry_pending_at),
  }));
}

// Read back hand edits, then regenerate. `domains` defaults to every domain that has ever had an item,
// so a list is never created for a domain nothing has been learned about. Projects are given as
// [{ id, root, name }]; only project-scope items for that project are written into its file, and
// shared files contain shared items only.
export function syncChecklistFiles(store, { sharedDir, domains = null, projects = [] }) {
  if (!sharedDir) throw new Error("syncChecklistFiles needs sharedDir.");
  const report = { written: [], retired: [], updated: [], unlinked: [] };
  const merge = (result, filePath) => {
    report.retired.push(...result.retired);
    report.updated.push(...result.updated);
    report.unlinked.push(...result.unlinked.map((text) => ({ file: filePath, text })));
  };
  const domainList = domains || store.db.prepare("SELECT DISTINCT domain FROM checklist_items WHERE scope = 'shared' ORDER BY domain").all().map((row) => row.domain);
  for (const domain of domainList) {
    const filePath = sharedChecklistPath(sharedDir, domain);
    const allowed = new Set(store.db.prepare("SELECT id FROM checklist_items WHERE scope = 'shared' AND domain = ?").all(domain).map((row) => row.id));
    merge(readBack(store, filePath, allowed), filePath);
    const content = renderChecklistMarkdown({ title: `${domain} checklist`, items: exportItems(store, "i.scope = 'shared' AND i.domain = ?", [domain]) });
    if (writeIfChanged(filePath, content)) report.written.push(filePath);
  }
  for (const project of projects) {
    const hasItems = store.db.prepare("SELECT 1 FROM checklist_items WHERE scope = 'project' AND project_id = ? LIMIT 1").get(project.id);
    const filePath = projectChecklistPath(project.root);
    if (!hasItems && !existsSync(filePath)) continue; // optional: never create an empty project file
    const allowed = new Set(store.db.prepare("SELECT id FROM checklist_items WHERE scope = 'project' AND project_id = ?").all(project.id).map((row) => row.id));
    merge(readBack(store, filePath, allowed), filePath);
    const content = renderChecklistMarkdown({ title: `${project.name || "Project"} checklist`, items: exportItems(store, "i.scope = 'project' AND i.project_id = ?", [project.id]) });
    if (writeIfChanged(filePath, content)) report.written.push(filePath);
  }
  return report;
}
